### ISSUE TITLE
Change Default Cart Donation Amounts

### ISSUE THREAD

**Issue by zherring** [FUNDOSS/fundoss#10]
We're already seeing a lot of folks customize below $10. I think we should give them a $5 option and remove the top most to reduce cognitive load. 

CURRENT
![Screen Shot 2021-06-10 at 07 52 59](https://user-images.githubusercontent.com/2172549/121537116-e2265980-c9c0-11eb-95ea-ee0904c4fcc8.png)

DESIRED
![Screen Shot 2021-06-10 at 07 51 23](https://user-images.githubusercontent.com/2172549/121537147-e94d6780-c9c0-11eb-8f00-74461f11901b.png)

**Comment by humanific** [comment]
done
