### ISSUE TITLE
捐赠付款

### ISSUE THREAD

**Issue by xiao1975** [FUNDOSS/fundoss#11]
为什么捐赠用银行卡美元而不是加密货币？这违背加密社区的初衷

**Comment by xiao1975** [comment]
用加密货币付款最好

**Comment by zherring** [comment]
Hi Xiao, 

Really appreciate the feedback. I'm relying on Google Translate (so apologies if I get this wrong) but it sounds like you want a crypto option to donate? We do too! It's on the roadmap, as well as a feature already included in Open Collective via (I believe) Bitpay but we had to prioritize payment options based on what the majority of the web2 users had, which were credit cards. 

Gitcoin CLR Round 10 is launching next week though! So we're hoping the teams who want to manage a crypto treasury on top of a regular fiat one will be participating there as well.

Out of curiosity, if we could only support 1-3 crypto currencies in V2, what would you want us to prioritize (including ERC20 stable coins, so if DAI and USDC were two separate requests). 

Thanks again for your feedback!

Regards,
Zach

**Comment by liangyue101** [comment]
I hope btc eth Stablecoin（usdt dai  usdc and so ）
