### ISSUE TITLE
stucking at verfiying payment data

### ISSUE THREAD

**Issue by angryolk** [FUNDOSS/fundoss#13]
hi, i would like to donate to the projects, but when i want to process the payment, it stuck at the " verifying the payment data"... and i have been waiting for 10 min, without any further process.  what's happening?

**Comment by zherring** [comment]
@angryolk So sorry you're running into that! Could you provide some more details?
- Mobile or Desktop?
- What browser?

Could you also, if you're on desktop, pull up the console and take a screen cap of any error logs?

**Comment by angryolk** [comment]
Desktop, Lastest chrome.  i have surpass the issue. as i have split the donation to 3 times. it works. you may add a max project donation per time.

**Comment by zherring** [comment]
@angryolk I wasn't aware there was that! We can definitely add that warning. How many collectives were you donating to and what were the amounts?

Thank you for the feedback!!

**Comment by hrj** [comment]
@zherring A friend who was trying to donate had the same issue, I think. Quoting:

> Somehow it didn't go thru.  I entered all my info but it still shows the payment as pending.  Dunno, I have never done anything like this via github.  Just tried again: I get to 'checkout' enter my credit card info, but it just keeps cycling around:


Screenshot:


![fundOss-dglnljjgbgkjhina](https://user-images.githubusercontent.com/345879/121716030-30407780-cafd-11eb-97e9-a3308def0339.png)

**Comment by zherring** [comment]
@hrj That is very odd! It looks like they only had one item in their shopping cart based on this screenshot, so it's probably a different issue than the problem noted above. If your friend has time, could they provide
- Platform
- Browser
- (if possible) console log?

Also curious if they have any browser plugins that might be hanging up the Stripe API?

**Comment by hrj** [comment]
@zherring Oh I thought this issue was about the amount being too large, but now I realize the splitting was necessary to reduce the number of projects per transaction, not the amount per transaction.

In any case, will let you know if I get more details from them.

**Comment by angryolk** [comment]
> @angryolk I wasn't aware there was that! We can definitely add that warning. How many collectives were you donating to and what were the amounts?
> 
> Thank you for the feedback!!

all of the 56 project in 1 cart, each 2 usd donation.

**Comment by zherring** [comment]
> > @angryolk I wasn't aware there was that! We can definitely add that warning. How many collectives were you donating to and what were the amounts?
> > Thank you for the feedback!!
> 
> all of the 56 project in 1 cart, each 2 usd donation.

Interesting! I did this in dev without any problems but we were using Stripe's test API. 🤔 I wonder if the live API might be hurting it... Let me test that again. How many was the max amount in the cart you could do? 25?
