### ISSUE TITLE
Project Cabal missing description (provided in this issue tho!)

### ISSUE THREAD

**Issue by cblgh** [FUNDOSS/fundoss#3]
Hi, thanks for yr hard work!

Our project [Cabal](https://opencollective.com/cabal-club) is missing a description on the [fundoss frontpage](https://fundoss.org/), despite having sent it to the project manager :)

Here are the previously requested project outlines:

140 chars:
Cabal is a peer-to-peer application for resilient and secure group communication that works in limited connectivity and when offline.

500 chars:
Cabal is a peer-to-peer application for resilient and secure group communication that works in limited connectivity and when offline. It has persistent p2p-synced chat history, channels, and a subjective moderation system. Anyone can start using Cabal by running one of the clients on their computer and sharing the generated key with people they want to chat with. There are no accounts and no servers; the only infrastructure required to keep chatting is the computers of the participants.

Thanks again!

**Comment by zherring** [comment]
Hi @cblgh ! We're pulling all descriptions from the OSC api so that teams can manage their own content in a single place. Please update your short and long descriptions on OSC to see it populate on FundOSS! 

Thanks!

**Comment by ocdtrekkie** [comment]
@zherring You might want to broadcast that to folks participating, as we were asked to send them to FundOSS by email! I will go ahead and update our OSC description now though.

**Comment by zherring** [comment]
> @zherring You might want to broadcast that to folks participating, as we were asked to send them to FundOSS by email! I will go ahead and update our OSC description now though.

I was not aware of that! Thank you for the heads up! Will pass this along. 👍

**Comment by cblgh** [comment]
After your advice @zherring, I updated our collective's short description in the collective settings, but it looks like the fundoss description hasn't been updated yet—might be good to know about!
