### ISSUE TITLE
Main page not showing up

### ISSUE THREAD

**Issue by spm32** [FUNDOSS/fundoss#43]
When I go to fundoss.org I currently only see the following:

https://gyazo.com/09a00fb0d360c61f7260424d2579f3c9

Is this a known issue?

**Comment by BenJam** [comment]
thanks @ceresstation I'll follow it up.

**Comment by gusaus** [comment]
@BenJam It looks like https://fundoss.org/ has been down for several weeks. I referenced https://github.com/FUNDOSS/fundoss/issues/42#issuecomment-1405876576 and a few times in Slack, but no recent response from those who control regarding future plans. 

If OSC has indeed lost interest, maybe we could explore bringing it back with other partners?

**Comment by gusaus** [comment]
Closing after realizing https://github.com/FUNDOSS/fundoss/issues/45 is a duplicate issue (posted in the wrong repo). Will transfer here.
