### ISSUE TITLE
Your Cart Check-Out - Updated Design

### ISSUE THREAD

**Issue by zherring** [FUNDOSS/fundoss#7]
**Current**
![image](https://user-images.githubusercontent.com/2172549/121069869-3ba54300-c78b-11eb-845a-a4dbf2f14c13.png)

**Desired**
![image](https://user-images.githubusercontent.com/2172549/121069933-4e1f7c80-c78b-11eb-8d96-438fb9a7d513.png)

**Comment by humanific** [comment]
![image](https://user-images.githubusercontent.com/1953897/121131358-dd936100-c859-11eb-973f-1b1479da0c58.png)

**Comment by humanific** [comment]
or like this
![image](https://user-images.githubusercontent.com/1953897/121160492-57394800-c876-11eb-9ca5-c2171771c3ed.png)
